package web.page;

public enum PageNameEnum {
	PresentedToPage,PlanADigitalROICalculatorPage,PlanALifetimeValuedPage,PlanBMediaPage,PlanAMediaPage,TeamCommitmentPage,MarketPlaceCompetitionPage,PlanAProposedPage, PlanBProposedPage
	,ClientObjectivesOnePage, StrategicMarketingPageOne, StrategicMarketingPageTwo, StrategicMarketingPageThree, StrategicMarketingPageFour;
}
