package web.page;

public enum PageNameEnum {
	PresentedToPage,PlanALifetimeValuedPage,PlanBMediaPage,PlanAMediaPage,TeamCommitmentPage,MarketPlaceCompetitionPage,PlanAProposedPage
	,ClientObjectivesOnePage, StrategicMarketingPageOne, StrategicMarketingPageTwo, StrategicMarketingPageThree, StrategicMarketingPageFour;
}
