package web.page;

public enum PageNameEnum {
	ConfidentialClientEvaluationOnePage,PresentedToPage,PlanADigitalROICalculatorPage,PlanBDigitalROICalculatorPage,PlanALifetimeValuedPage,PlanBMediaPage,PlanAMediaPage,TeamCommitmentPage,MarketPlaceCompetitionPage,PlanAProposedPage, PlanBProposedPage
	,ClientObjectivesOnePage, StrategicMarketingPageOne, StrategicMarketingPageTwo, StrategicMarketingPageThree, StrategicMarketingPageFour;
}
