package web.page;

import java.util.List;
import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import java.util.logging.Logger;
import web.page.*;
import web.model.WizardData;
import web.page.presentedtopage.PresentedToPageController;
import web.page.presentedtopage.PresentedToPageModel;
import web.repository.WizardDataRepository;

@Controller    // This means that this class is a Controller
public class PublishController {
	private static final Logger mLog = Logger.getLogger(PresentedToPageController.class.getName());
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardDataRepository wizardDataRepository;
	
	@RequestMapping(value = "/Publish", method = RequestMethod.GET)
	public String detail(Model model, @RequestParam String ID) {
		Integer idInt = Integer.parseInt(ID);
		//get all 
		Iterable<WizardData> dataPages = wizardDataRepository.findByWizardid(idInt);
	    for (WizardData data : dataPages) {
	    	//pull of data model
	    	PageNameEnum pageName = PageNameEnum.valueOf(data.getPagename());
	    	mLog.info("page name = " + pageName);
	    	switch (pageName) {
	    	case PresentedToPage:
	    		PresentedToPageModel presentedToPageModel = null;
	    		
	    		presentedToPageModel =(PresentedToPageModel)JSONManager.convertFromJson(data.getPagedata(), PresentedToPageModel.class);
	    		model.addAttribute("PresentedToPage", presentedToPageModel);	
	    		
	    		mLog.info("found page PresentedToPage");
	    		break;
	    	case TeamCommitmentPage:
	    		mLog.info("found page PresentedToPage");
	    		break;
	    	}
	    	
	    }
		
		return "publish";
	}

}
