package web.page.clientobjectivesonepage;
import java.util.Optional;
import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import web.model.Wizard;
import web.model.WizardData;
import web.page.Pages;
import web.page.JSONManager;
import web.page.PageNameEnum;
import web.page.presentedtopage.PresentedToPageModel;
import web.page.teamcommitmentpage.TeamCommitmentPageController;
import web.page.teamcommitmentpage.TeamCommitmentPageModel;
import web.repository.WizardDataRepository;
import web.repository.WizardRepository;
@Controller    // This means that this class is a Controller
public class ClientObjectivesOnePageControl {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardRepository wizardRepository;
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardDataRepository wizardDataRepository;

	private static final Logger mLog = Logger.getLogger(TeamCommitmentPageController.class.getName());
	@RequestMapping(value = "/ClientObjectivesOnePage", method = RequestMethod.GET)
	public String detail(Model model, @RequestParam String ID) {
		mLog.info("starting detail");
		//get wizard header 
		Optional<Wizard> wizardOpt = wizardRepository.findById(Integer.valueOf(ID));
		Wizard wizard = wizardOpt.orElse(null);
		WizardData wizardData = wizardDataRepository.findByPagesequenceAndWizardid(Pages.CLIENTOBJECTIVESONEPAGE.getPageSequence(), wizard.getWizardid());
		ClientObjectivesOnePageModel dataPageModel = null;
		if (wizardData != null) {
			dataPageModel =(ClientObjectivesOnePageModel) JSONManager.convertFromJson(wizardData.getPagedata(),ClientObjectivesOnePageModel.class);
		}
		//DemographicManager.convertFromJson(json)
		model.addAttribute("wizardData", wizardData);
		model.addAttribute("dataPageModel", dataPageModel);
		model.addAttribute("wizard", wizard);
		return "pages/ClientObjectivesOnePage";
	}
	/*
	 * ivate String ;
	private String ;
	private String ;
	private String ;
	private String thirdLevelName;
	private String ;
	private String ;
	private String fourthLevelTitle;
	 */
	@RequestMapping(value = "/saveClientObjectivesOnePage", method = RequestMethod.POST)
	public String save(@RequestParam String wizardId
			,@RequestParam(defaultValue = "false") boolean introduceNewDepartment
			,@RequestParam(defaultValue = "false") boolean featureSpecificProducts
			,@RequestParam(defaultValue = "false") boolean callAttentiontoBrandsPrivateLabelsCarried
			,@RequestParam(defaultValue = "false") boolean promoteOffPriceItemsServices
			,@RequestParam(defaultValue = "false") boolean retainCurrentConsumers
			,@RequestParam(defaultValue = "false") boolean increaseCustomerVisits
			,@RequestParam(defaultValue = "false") boolean increaseTrafficLeadCalls
			,@RequestParam(defaultValue = "false") boolean expandTargetConsumers
			,@RequestParam(defaultValue = "false") boolean changeConsumerAttitudes
			,@RequestParam(defaultValue = "false") boolean makePromotionalEventsStronger
			,@RequestParam(defaultValue = "false") boolean increaseDigitalMobileOnlineResponse
			,@RequestParam(defaultValue = "false") boolean developAQuarterlySpike
			,@RequestParam(defaultValue = "false") boolean developDatabaseMarketing
			,@RequestParam(defaultValue = "false") boolean initiateCauseMarketingProgram
			,@RequestParam(defaultValue = "false") boolean developSpeciallyStagedEvent
			,@RequestParam(defaultValue = "false") boolean maintainMarketDominance
			,@RequestParam(defaultValue = "false") boolean improveBusinessNameBrand
			,@RequestParam(defaultValue = "false") boolean establishorReestablishBusinessImage
			,@RequestParam(defaultValue = "false") boolean createPentUpDemand
			,@RequestParam(defaultValue = "false") boolean increaseMarketShare
			,@RequestParam(defaultValue = "false") boolean other
			,@RequestParam(defaultValue = "0") int introduceNewDepartmentSortOrder
			,@RequestParam(defaultValue = "0") int  featureSpecificProductsSortOrder
			,@RequestParam(defaultValue = "0") int  callAttentiontoBrandsPrivateLabelsCarriedSortOrder
			,@RequestParam(defaultValue = "0") int  promoteOffPriceItemsServicesSortOrder
			,@RequestParam(defaultValue = "0") int  retainCurrentConsumersSortOrder
			,@RequestParam(defaultValue = "0") int increaseCustomerVisitsSortOrder
			,@RequestParam(defaultValue = "0") int  increaseTrafficLeadCallsSortOrder
			,@RequestParam(defaultValue = "0") int  expandTargetConsumersSortOrder
			,@RequestParam(defaultValue = "0") int  changeConsumerAttitudesSortOrder
			,@RequestParam(defaultValue = "0") int makePromotionalEventsStrongerSortOrder
			,@RequestParam(defaultValue = "0") int increaseDigitalMobileOnlineResponseSortOrder
			,@RequestParam(defaultValue = "0") int developAQuarterlySpikeSortOrder
			,@RequestParam(defaultValue = "0") int developDatabaseMarketingSortOrder
			,@RequestParam(defaultValue = "0") int initiateCauseMarketingProgramSortOrder
			,@RequestParam(defaultValue = "0") int developSpeciallyStagedEventSortOrder
			,@RequestParam(defaultValue = "0") int maintainMarketDominanceSortOrder
			,@RequestParam(defaultValue = "0") int improveBusinessNameBrandSortOrder
			,@RequestParam(defaultValue = "0") int establishorReestablishBusinessImageSortOrder
			,@RequestParam(defaultValue = "0") int createPentUpDemandSortOrder
			,@RequestParam(defaultValue = "0") int increaseMarketShareSortOrder
			,@RequestParam(defaultValue = "0") int otherSortOrder  
			,@RequestParam String wizarddataid
			,@RequestParam String previousPage
			,@RequestParam String publishPage
			,@RequestParam(required=false, value="next") String next
			,@RequestParam(required=false, value="publish") String publish
			,@RequestParam(required=false, value="previous") String previous
			,@RequestParam String nextPage) {
		mLog.info("starting save");
		
		//internal next page or publish
		String internalNextPage = nextPage;
		if (publish != null) {
					internalNextPage= publishPage;
		}
		if (previous != null) {
			internalNextPage= previousPage;
        }
		 
		WizardData wizardData = new WizardData();
		wizardData.setPagename(PageNameEnum.ClientObjectivesOnePage.toString());
		wizardData.setPagesequence(Pages.CLIENTOBJECTIVESONEPAGE.getPageSequence());
		if (wizarddataid != null && wizarddataid.trim().length() > 0 ) {
			Integer wizardDataInt = Integer.valueOf(wizarddataid);
			wizardData.setWizarddataid(wizardDataInt);
		}
		Integer wizardIdInt = Integer.valueOf(wizardId);
		wizardData.setWizardid(wizardIdInt);
		
		ClientObjectivesOnePageModel pageModel = new ClientObjectivesOnePageModel(introduceNewDepartment, featureSpecificProducts,
				callAttentiontoBrandsPrivateLabelsCarried, promoteOffPriceItemsServices,
				retainCurrentConsumers, increaseCustomerVisits, increaseTrafficLeadCalls,
				expandTargetConsumers, changeConsumerAttitudes, makePromotionalEventsStronger,
				increaseDigitalMobileOnlineResponse, developAQuarterlySpike,
				developDatabaseMarketing, initiateCauseMarketingProgram,
				developSpeciallyStagedEvent, maintainMarketDominance, improveBusinessNameBrand,
				establishorReestablishBusinessImage, createPentUpDemand, increaseMarketShare,
				other,introduceNewDepartmentSortOrder, featureSpecificProductsSortOrder,
				callAttentiontoBrandsPrivateLabelsCarriedSortOrder, promoteOffPriceItemsServicesSortOrder,
				retainCurrentConsumersSortOrder, increaseCustomerVisitsSortOrder, increaseTrafficLeadCallsSortOrder,
				expandTargetConsumersSortOrder, changeConsumerAttitudesSortOrder, makePromotionalEventsStrongerSortOrder,
				increaseDigitalMobileOnlineResponseSortOrder, developAQuarterlySpikeSortOrder,
				developDatabaseMarketingSortOrder, initiateCauseMarketingProgramSortOrder,
				developSpeciallyStagedEventSortOrder, maintainMarketDominanceSortOrder, improveBusinessNameBrandSortOrder,
				establishorReestablishBusinessImageSortOrder, createPentUpDemandSortOrder, increaseMarketShareSortOrder,
				otherSortOrder);

		String pageData = JSONManager.convertToJson(pageModel);
		wizardData.setPagedata(pageData);
		wizardDataRepository.save(wizardData);
		//model.addAttribute("wizard", wizard);
		return internalNextPage;
	}
	
}
