package web.page.strategicmarketingpagetwo;

import java.util.Optional;
import java.util.logging.Logger;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import web.model.Wizard;
import web.model.WizardData;
import web.page.Pages;

import web.page.JSONManager;
import web.page.PageNameEnum;
import web.repository.WizardDataRepository;
import web.repository.WizardRepository;
import web.util.EncryptionDecryptionManager;

@Controller // This means that this class is a Controller
public class StrategicMarketingPageTwoController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardRepository wizardRepository;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardDataRepository wizardDataRepository;

	private static final Logger mLog = Logger.getLogger(StrategicMarketingPageTwoController.class.getName());

	@RequestMapping(value = "/StrategicMarketingPageTwo", method = RequestMethod.GET)
	public String detail(Model model, @RequestParam String ID, HttpSession session) {
		mLog.info("starting detail");
		String decryptID = session.getAttribute("ID").toString();
		mLog.info("decryptID " + decryptID);
		// get wizard header
		Optional<Wizard> wizardOpt = wizardRepository.findById(Integer.valueOf(decryptID));
			Wizard wizard = wizardOpt.orElse(null);
		WizardData wizardData = wizardDataRepository
				.findByPagesequenceAndWizardid(Pages.StrategicMarketingTwo.getPageSequence(), wizard.getWizardid());
		StrategicMarketingPageTwoModel dataPageModel = null;
		if (wizardData != null) {
			dataPageModel = (StrategicMarketingPageTwoModel) JSONManager.convertFromJson(wizardData.getPagedata(),
					StrategicMarketingPageTwoModel.class);

		}
		// DemographicManager.convertFromJson(json)
		model.addAttribute("wizardData", wizardData);
		model.addAttribute("dataPageModel", dataPageModel);
		model.addAttribute("wizard", wizard);
		return "pages/StrategicMarketingPageTwo";
	}

	@RequestMapping(value = "/saveStrategicMarketingPageTwo", method = RequestMethod.POST)
	public String save(@RequestParam String wizardId, @RequestParam String wizarddataid,
			@RequestParam(value = "excluded", required = false) String excluded,
			@RequestParam(required = false, value = "competitionA", defaultValue = "") String competitionA,
			@RequestParam(required = false, value = "competitionB", defaultValue = "") String competitionB,
			@RequestParam(required = false, value = "currentCompanySlogan", defaultValue = "") String currentCompanySlogan,
			@RequestParam(required = false, value = "competitionWeaknessA", defaultValue = "") String competitionWeaknessA,
			@RequestParam(required = false, value = "competitionWeaknessB", defaultValue = "") String competitionWeaknessB,
			@RequestParam(required = false, value = "competitionStrengthA", defaultValue = "") String competitionStrengthA,
			@RequestParam(required = false, value = "competitionStrengthB", defaultValue = "") String competitionStrengthB,
			@RequestParam(required = false, value = "companyNameProjectImage", defaultValue = "") String companyNameProjectImage,
			@RequestParam(value = "companySloganProjectImage", defaultValue = "false") boolean companySloganProjectImage,
			@RequestParam String nextPage, @RequestParam String publishPage, @RequestParam String previousPage,
			@RequestParam(required = false, value = "previous") String previous,
			@RequestParam(required = false, value = "next") String next,
			@RequestParam(required = false, value = "publish") String publish, HttpSession session) {
		mLog.info("starting save");
		mLog.info("competitionA [" + competitionA + "]");
		mLog.info("competitionB [" + competitionB + "]");
		mLog.info("currentCompanySlogan [" + currentCompanySlogan + "]");
		mLog.info("competitionWeaknessA [" + competitionWeaknessA + "]");
		mLog.info("competitionWeaknessB [" + competitionWeaknessB + "]");
		mLog.info("competitionStrengthA [" + competitionStrengthA + "]");
		mLog.info("competitionStrengthB [" + competitionStrengthB + "]");
		mLog.info("companyNameProjectImage [" + companyNameProjectImage + "]");

		// internal next page or publish
		String internalNextPage = nextPage;
		if (publish != null) {
			internalNextPage = publishPage;
		}
		if (previous != null) {
			internalNextPage = previousPage;
		}

		WizardData wizardData = new WizardData();
		boolean shouldExclude = excluded != null ? true: false;
		wizardData.setExcluded(shouldExclude);
		wizardData.setPagename(PageNameEnum.StrategicMarketingPageTwo.toString());
		wizardData.setPagesequence(Pages.StrategicMarketingTwo.getPageSequence());
		if (wizarddataid != null && wizarddataid.trim().length() > 0) {
			Integer wizardDataInt = Integer.valueOf(wizarddataid);
			wizardData.setWizarddataid(wizardDataInt);
		}
		wizardId = session.getAttribute("ID").toString();
		Integer wizardIdInt = Integer.valueOf(wizardId);
		wizardData.setWizardid(wizardIdInt);
		StrategicMarketingPageTwoModel pageModel = new StrategicMarketingPageTwoModel(competitionA, competitionB,
				competitionStrengthA, competitionStrengthB, competitionWeaknessA, competitionWeaknessB,
				companyNameProjectImage, currentCompanySlogan, companySloganProjectImage);
		String pageData = JSONManager.convertToJson(pageModel);

		wizardData.setPagedata(pageData);
		wizardDataRepository.save(wizardData);
		// model.addAttribute("wizard", wizard);
		return internalNextPage;
	}
}
