package web.page.targetmarketingpage;
import java.util.Optional;
import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import web.model.Wizard;
import web.model.WizardData;
import web.page.Pages;

import web.page.JSONManager;
import web.page.PageNameEnum;
import web.repository.WizardDataRepository;
import web.repository.WizardRepository;


@Controller    // This means that this class is a Controller
public class TargetMarketingPageController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardRepository wizardRepository;
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WizardDataRepository wizardDataRepository;

	private static final Logger mLog = Logger.getLogger(TargetMarketingPageController.class.getName());
	@RequestMapping(value = "/TargetMarketingPage", method = RequestMethod.GET)
	public String detail(Model model, @RequestParam String ID) {
		mLog.info("starting detail");
		//get wizard header 
		Optional<Wizard> wizardOpt = wizardRepository.findById(Integer.valueOf(ID));
		Wizard wizard = wizardOpt.orElse(null);
		WizardData wizardData = wizardDataRepository.findByPagesequenceAndWizardid(Pages.TargetMarketingPage.getPageSequence(), wizard.getWizardid());
		TargetMarketingPageModel dataPageModel = null;
		if (wizardData != null) {
			dataPageModel =(TargetMarketingPageModel)JSONManager.convertFromJson(wizardData.getPagedata(), TargetMarketingPageModel.class);
			
		}
		//DemographicManager.convertFromJson(json)
		model.addAttribute("wizardData", wizardData);
		model.addAttribute("dataPageModel", dataPageModel);
		model.addAttribute("wizard", wizard);
		return "pages/TargetMarketingPage";
	}
	
	
	@RequestMapping(value = "/saveTargetMarketingPage", method = RequestMethod.POST)
	public String save(@RequestParam String wizardId
			,@RequestParam String wizarddataid
			,@RequestParam int pctMen
			,@RequestParam int pctWomen
			,@RequestParam int householdIncome
			,@RequestParam String describeIdealTargetConsumer
			,@RequestParam int have12to18
			,@RequestParam int have19to25
			,@RequestParam int have26to35
			,@RequestParam int have36to45
			,@RequestParam int have46to55
			,@RequestParam int have56Plus
			,@RequestParam int want12to18
			,@RequestParam int want19to25
			,@RequestParam int want26to35
			,@RequestParam int want36to45
			,@RequestParam int want46to55
			,@RequestParam int want55Plus
			,@RequestParam String nextPage
			,@RequestParam String publishPage
			,@RequestParam String previousPage
			,@RequestParam(required=false, value="previous") String previous
			,@RequestParam(required=false, value="next") String next
	        ,@RequestParam(required=false, value="publish") String publish){
		
		//internal next page or publish
		String internalNextPage = nextPage;
		if (publish != null) {
					internalNextPage= publishPage;
		}
		if (previous != null) {
			internalNextPage= previousPage;
                 }
		
		
		WizardData wizardData = new WizardData();
	    wizardData.setPagename(PageNameEnum.TargetMarketingPage.toString());
		wizardData.setPagesequence(Pages.TargetMarketingPage.getPageSequence());
		if (wizarddataid != null && wizarddataid.trim().length() > 0 ) {
			Integer wizardDataInt = Integer.valueOf(wizarddataid);
			wizardData.setWizarddataid(wizardDataInt);
		}
		Integer wizardIdInt = Integer.valueOf(wizardId);
		wizardData.setWizardid(wizardIdInt);
		TargetMarketingPageModel pageModel  = new TargetMarketingPageModel(pctMen, pctWomen, householdIncome,	describeIdealTargetConsumer, have12to18, have19to25, have26to35, have36to45, have46to55, have56Plus, want12to18, want19to25, want26to35, want36to45, want46to55, want55Plus);
		String pageData = JSONManager.convertToJson(pageModel);
		
		wizardData.setPagedata(pageData);
		wizardDataRepository.save(wizardData);
		//model.addAttribute("wizard", wizard);
		return internalNextPage;
	}
}
